### ISSUE TITLE
Android: branch.json not being picked up

### ISSUE THREAD

**Issue by a-koka** [BranchMetrics/react-native-branch-deep-linking#336]
Looks like the app crashes when `AndroidManifest.xml` is missing the keys below. `iOS` seems to pick these values up from `branch.json` just fine.

```
        <!-- Branch init -->
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_abc" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_abc" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />
```

Any ideas how to have Android pick these up from the json file?

**Comment by sequoiaat** [comment]
Hello, We are working on supporting these keys in JSON file in Android. We will get back to you soon. Thanks.

**Comment by kyle-ssg** [comment]
Is there an update on this? The docs seem to suggest that adding branch.json inside android/app/src/main/assets/would work, however it doesn't as far as I can see

**Comment by sequoiaat** [comment]
Hello, We are still working on it. We will release a fix soon.

**Comment by yamov** [comment]
Hi, @sequoiaat. Any estimates of when the fix will be released?

**Comment by dozoisch** [comment]
Any updates on this @sequoiaat ?

**Comment by stenmuchow** [comment]
+1

**Comment by dbelchev** [comment]
Hey @sequoiaat,
This is still an issue today.

**Comment by jdee** [comment]
Keys are not supported in branch.json for Android. In fact, they were never officially supported at all for this SDK because they cannot be supported on Android at all. They happen to work on iOS, but since they can't be supported on Android, there was never any official announcement of support afaik. We'll address this in 3.0, but it may probably require native SDK changes. Along the way we'll also support setting keys from JS instead of configuration.

**Comment by jdee** [comment]
This has been addressed in the master branch by #417. Basically you need to replace `Branch.getAutoInstance(this)` in your MainApplication.java with `RNBranchModule.getAutoInstance(this)`. See webview_example for a working example that sets keys from branch.json. The Android and iOS apps do not have key entries in the Android manifest or Info.plist, respectively. This will go out soon in a 3.0.0-beta.2. It also lays the groundwork for setting keys from JS.

**Comment by mieszko4** [comment]
I made a proposal for docs since it was unclear to me that manual step is required when using RN > 0.60 with branch.json: https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/pull/520

**Comment by ryanbabbly** [comment]
This is still an issue for me using branch 5.0.0 and react native 0.63. I have a branch.json file next to my package.json that looks like this:

```
{
    "liveKey": "key_live_mykey",
    "testKey": "key_test_mykey",
    "debugMode": true,
    "useTestInstance": true
}
```

in the docs it says I can omit the keys from my AndroidManifest.xml if I have branch.json, but when I try to run the app I get: `Error from Branch: Trouble initializing Branch. Branch API Error: Please enter your branch_key in your project's manifest file first.`

This happens even if I manually link and ignore the warnings from react about using autolink instead.

**Comment by delventhalz** [comment]
Seeing the same issue with rn-branch 5.0 and RN 0.63. Branch on Android cannot pull keys from `branch.json`, only from `AndroidManifest.xml`. This is with `RNBranchModule.getAutoInstance(this)` being called in `MainApplication.java` like @jdee suggests.

**Comment by mgwedd** [comment]
I spent quite some time trying to understand why including this SDK on Android caused my app to crash on launch. Then I found this issue. Putting the keys in the AndroidManifest.xml fixes the issue it seems. Could someone update the Branch.io docs, which say that you can rely on branch.json for Android (and that's clearly not the case)? 

Here is what [the Branch RN docs](https://help.branch.io/developers-hub/docs/react-native#android-1) say: 
`        
        
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_gdzsepIaUf7wG3dEWb3aBkmcutm0PwJa"/>
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_edwDakKcMeWzJ3hC3aZs9kniyuaWGCTa"/>
      `
Using react-native@0.63.3, gradle@4.0.1, and react-native-branch@5.0.2.

**Comment by mnifakram** [comment]
This is still an issue on the latest sdk 5.0.3 and react native 0.64 and using `RNBranchModule.getAutoInstance(this)`. 
Please reopen.
