### ISSUE TITLE
'Branch/Branch.h' file not found when linking manually (re-opened)

### ISSUE THREAD

**Issue by theseansy** [BranchMetrics/react-native-branch-deep-linking#60]
After going through [these directions](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/installation.md#manual-linking), and installing Branch via Cocoapods, `RNBranch.m` still can't find `Branch/Branch.h`

I was able to get everything compiling by putting

```
#import <Branch-SDK/Branch.h>
```
...at the top of `RNBranch.m`, only after updating my `HEADER_SEARCH_PATHS` for `RNBranch.xcodeproj` to have `$(SRCROOT)/../../../ios/Pods/Branch` in it.

...Also while trying to figure this out, I realized [this documentation](https://dev.branch.io/getting-started/sdk-integration-guide/guide/react/) seems inconsistent as it uses `branch-react-native-sdk` and `react-native-branch` (two different modules) interchangeably in setting up the SDK (see screenshots).

**Comment by jdee** [comment]
This was addressed in 1.0.0, released Friday. Closing.

**Comment by evanjmg** [comment]
I'm still having issues with this on 2.3.3 - could there be some troubleshooting conclusion as to what to check in the README?

**Comment by OneStromberg** [comment]
@evanjmg which **pod** version are you using? Seems like the issue appears with pod version greater than _1.5.3_.
I just updated **pod** to version _1.6.1._ and got the issue.
